"""Client for the NiB (Norge i Bilder) ArcGIS token endpoint.

See https://www.geonorge.no/nib: tokens are generated by POSTing to
``/token/tilecache`` with HTTP Basic Auth (GeoID username/password) and a
form body describing the "client" (referer or ip) the token should be bound
to and its expiration in seconds.
"""

from __future__ import annotations

import logging

import httpx

from nib_proxy.client_key import ClientKey
from nib_proxy.config import Settings

logger = logging.getLogger(__name__)


class TokenRequestError(RuntimeError):
    """Raised when the NiB token endpoint fails to return a token."""


async def fetch_token(
    client: httpx.AsyncClient,
    settings: Settings,
    client_key: ClientKey,
) -> str:
    """Fetch a fresh NiB token for the given client key."""
    data = {
        "client": client_key.mode,
        "expiration": settings.token_validity_seconds,
        "f": "json",
    }
    if client_key.mode == "referer":
        data["referer"] = client_key.value
    else:
        data["ip"] = client_key.value

    response = await client.post(
        settings.token_url,
        data=data,
        auth=(settings.nib_username, settings.nib_password),
    )
    response.raise_for_status()
    payload = response.json()
    token = payload.get("token")
    if not token:
        message = f"NiB token endpoint did not return a token: {payload}"
        raise TokenRequestError(message)
    return token
