"""Client for the NiB (Norge i Bilder) ArcGIS token endpoint.

Per the "NiB Eksport API" backend
(https://backend-api.klienter-prod-k8s2.norgeibilder.no/swagger/v1/swagger.json),
tokens are generated by POSTing to ``/token/tilecache`` with HTTP Basic Auth
(GeoID username/password) and a form body describing the "client" the token
should be bound to and its expiration in seconds.

The ``client`` field accepts exactly three values (per the NiB token UI at
https://services.norgeibilder.no/token):

- ``"referer"``: bind the token to an HTTP Referer/domain (requires
  ``referer=<domain>``).
- ``"ip"``: bind the token to an explicit IP address (requires
  ``ip=<address>``).
- ``"requestip"``: bind the token to whichever IP address the token request
  itself is sent from (auto-detected server-side; ``ip``/``referer`` are
  ignored).

We always use ``"requestip"`` for IP-bound tokens (rather than ``"ip"`` with
an explicit address) because it's *this proxy* that later makes the actual
upstream WMS/WMTS requests, not the original browser/client behind it. NiB
sees the same egress IP for both the token request and the subsequent tile
requests, so ``"requestip"`` is the only mode that reliably matches. The
resolved client key (browser IP or Referer) is still used internally to
partition the token cache per origin, but is never sent to NiB in "ip" mode.
"""

from __future__ import annotations

import logging

import httpx

from nib_proxy.client_key import ClientKey
from nib_proxy.config import Settings

logger = logging.getLogger(__name__)


class TokenRequestError(RuntimeError):
    """Raised when the NiB token endpoint fails to return a usable token.

    Carries the raw upstream response so callers can propagate it verbatim
    (status code, headers, body) instead of masking it behind a generic 500,
    making it straightforward to debug against the real NiB service.
    """

    def __init__(self, message: str, response: httpx.Response) -> None:
        super().__init__(message)
        self.response = response


async def fetch_token(
    client: httpx.AsyncClient,
    settings: Settings,
    client_key: ClientKey,
) -> str:
    """Fetch a fresh NiB token for the given client key."""
    data = {
        "expiration": settings.token_validity_seconds,
        "f": "json",
    }
    if client_key.mode == "referer":
        data["client"] = "referer"
        data["referer"] = client_key.value
    else:
        # Bind to the IP this request is actually sent from (this proxy's
        # egress IP), since that's the IP NiB will also see on the
        # subsequent upstream tile requests. See module docstring.
        data["client"] = "requestip"

    logger.info(
        "Requesting NiB token: client=%s (cache_key=%s), expiration=%ds",
        data["client"],
        client_key.cache_key,
        settings.token_validity_seconds,
    )
    response = await client.post(
        settings.token_url,
        data=data,
        auth=(settings.nib_username, settings.nib_password),
    )
    if response.is_error:
        message = f"NiB token endpoint returned {response.status_code}: {response.text}"
        logger.warning(
            "NiB token request failed for %s: %d %s",
            client_key.cache_key,
            response.status_code,
            response.text,
        )
        raise TokenRequestError(message, response)

    payload = response.json()
    token = payload.get("token")
    if not token:
        message = f"NiB token endpoint did not return a token: {payload}"
        logger.warning(
            "NiB token endpoint returned no token for %s: %s",
            client_key.cache_key,
            payload,
        )
        raise TokenRequestError(message, response)

    logger.info(
        "Obtained NiB token for %s (token=%s..., length=%d)",
        client_key.cache_key,
        token[:6],
        len(token),
    )
    return token
